"""add row_hash to worklogs

Revision ID: 3712d817fd05
Revises: f5273d92225b
Create Date: 2026-03-31 19:20:41.022464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3712d817fd05'
down_revision = 'f5273d92225b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_clients_name', ['name'])

    with op.batch_alter_table('landmen', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.create_unique_constraint('uq_landmen_name', ['name'])

    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('prospect_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expense_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('legal_description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('well_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('work_performed_detail', sa.Text(), nullable=True))
        batch_op.alter_column('work_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_worklogs_row_hash'), ['row_hash'], unique=True)
        batch_op.create_foreign_key('fk_worklogs_prospect_id', 'prospects', ['prospect_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_worklogs_prospect_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_worklogs_row_hash'))
        batch_op.alter_column('work_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('work_performed_detail')
        batch_op.drop_column('well_name')
        batch_op.drop_column('legal_description')
        batch_op.drop_column('county')
        batch_op.drop_column('status')
        batch_op.drop_column('expense_total')
        batch_op.drop_column('prospect_id')
        batch_op.drop_column('row_hash')

    with op.batch_alter_table('landmen', schema=None) as batch_op:
        batch_op.drop_constraint('uq_landmen_name', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_name', type_='unique')

    op.drop_table('prospects')
    # ### end Alembic commands ###
