"""add state column to worklogs

Revision ID: 44c823df3dd4
Revises: 3712d817fd05
Create Date: 2026-03-31 20:06:39.996317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c823df3dd4'
down_revision = '3712d817fd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
